App\Domain\Post:
    type:   entity
    table:  post
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type:   string
            length: 255
            nullable: true
        url:
            type:   string
            length: 255
        createdAt:
            type: datetime
