App\Bundle\MainBundle\Entity\Submission:
    repositoryClass:    App\Bundle\MainBundle\Entity\Post\SubmissionRepository
    type:               entity
    table:              submission
    id:
        identifier:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type:   string
            length: 255
        gfycatKey:
            type:   string
            length: 255
        baseUrl:
            type:   string
            length: 255
        author:
            type:       string
            length:     255
            nullable:   true
        createdAt:
            type: datetime
