app_main_post:
    resource: "@AppMainBundle/Resources/config/Post/routing.yml"
    prefix:   /

app_main_post_vote:
    resource: "@AppMainBundle/Resources/config/Post/Vote/routing.yml"
    prefix:   /

app_main_submission:
    resource: "@AppMainBundle/Resources/config/Submission/routing.yml"
    prefix:   /

app_main_homepage:
    path:     /
    defaults: { _controller: AppMainBundle:Homepage:index }
