services:
    app_main.post.reader:
        class: App\Bundle\MainBundle\Services\Post\DoctrineReader
        arguments:
            - @doctrine.orm.entity_manager
    app_main.post.writer:
        class: App\Bundle\MainBundle\Services\Post\DoctrineWriter
        arguments:
            - @doctrine.orm.entity_manager
    app_main.post.factory:
        class: App\Bundle\MainBundle\Services\Post\Factory
        arguments:
            - @app_main.clock
    app_main.clock:
        class: App\Bundle\MainBundle\Infrastructure\Clock\Clock
