<?php

namespace App\Bundle\MainBundle\Entity\Post\Vote\Upvote;

use Doctrine\ORM\EntityRepository;

/**
 * CompiledRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompiledRepository extends EntityRepository
{
    /**
     * Add one to the quantity of upvotes for the given reference or create a
     * compilation if it does not exist yet
     *
     * @param int $reference
     */
    public function addUpvote($reference)
    {
        $builder = $this->createQueryBuilder('compiled');
        $builder
            ->where('compiled.reference = :reference')
            ->setParameter('reference', $reference)
        ;

        $compiled = $builder->getQuery()->getOneOrNullResult();

        if ($compiled === null) {
            $compiled = new Compiled();
            $compiled->setReference($reference);
        }

        $compiled->setQuantity($compiled->getQuantity() + 1);

        $this->getEntityManager()->persist($compiled);
        $this->getEntityManager()->flush($compiled);
    }
}
