<?php

namespace App\Bundle\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubmissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubmissionRepository extends EntityRepository
{
    /**
     * Save the given entity in database
     *
     * @param Submission $submission
     */
    public function save(Submission $submission)
    {
        $this->getEntityManager()->persist($submission);
        $this->getEntityManager()->flush($submission);
    }

    /**
     * Find the submission having the given identifier
     *
     * @return Submission|null
     */
    public function findByIdentifier($identifier)
    {
        $builder = $this->createQueryBuilder('submission');
        $builder
            ->where('submission.id = :identifier')
            ->setParameter('identifier', $identifier)
        ;

        return $builder->getQuery()->getOneOrNullResult();
    }
}
